# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'barbecue/ui/GainOffset.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1070, 680)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/imagery/barbecue_icon.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.frameControl = QtGui.QFrame(self.centralwidget)
        self.frameControl.setMinimumSize(QtCore.QSize(0, 0))
        self.frameControl.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frameControl.setFrameShape(QtGui.QFrame.Panel)
        self.frameControl.setFrameShadow(QtGui.QFrame.Raised)
        self.frameControl.setObjectName(_fromUtf8("frameControl"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frameControl)
        self.verticalLayout_2.setContentsMargins(-1, 0, 9, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelMainTitle = QtGui.QLabel(self.frameControl)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        self.labelMainTitle.setFont(font)
        self.labelMainTitle.setObjectName(_fromUtf8("labelMainTitle"))
        self.verticalLayout_2.addWidget(self.labelMainTitle)
        self.frame_6 = QtGui.QFrame(self.frameControl)
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(0, 9, 0, 9)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.toolButtonStart = QtGui.QToolButton(self.frame_6)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/greys/greys/forward.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonStart.setIcon(icon1)
        self.toolButtonStart.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonStart.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonStart.setObjectName(_fromUtf8("toolButtonStart"))
        self.horizontalLayout_6.addWidget(self.toolButtonStart)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.toolButtonStop = QtGui.QToolButton(self.frame_6)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/greys/greys/stop.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonStop.setIcon(icon2)
        self.toolButtonStop.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonStop.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonStop.setObjectName(_fromUtf8("toolButtonStop"))
        self.horizontalLayout_6.addWidget(self.toolButtonStop)
        self.labelProcessing = QtGui.QLabel(self.frame_6)
        self.labelProcessing.setWordWrap(True)
        self.labelProcessing.setObjectName(_fromUtf8("labelProcessing"))
        self.horizontalLayout_6.addWidget(self.labelProcessing)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.progressBar = QtGui.QProgressBar(self.frameControl)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_2.addWidget(self.progressBar)
        self.frame_2 = QtGui.QFrame(self.frameControl)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setMinimumSize(QtCore.QSize(64, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.spinBoxOffsetStart = QtGui.QSpinBox(self.frame_2)
        self.spinBoxOffsetStart.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBoxOffsetStart.setObjectName(_fromUtf8("spinBoxOffsetStart"))
        self.horizontalLayout_2.addWidget(self.spinBoxOffsetStart)
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.spinBoxOffsetEnd = QtGui.QSpinBox(self.frame_2)
        self.spinBoxOffsetEnd.setObjectName(_fromUtf8("spinBoxOffsetEnd"))
        self.horizontalLayout_2.addWidget(self.spinBoxOffsetEnd)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame = QtGui.QFrame(self.frameControl)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(64, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBoxGainStart = QtGui.QSpinBox(self.frame)
        self.spinBoxGainStart.setEnabled(False)
        self.spinBoxGainStart.setObjectName(_fromUtf8("spinBoxGainStart"))
        self.horizontalLayout.addWidget(self.spinBoxGainStart)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.spinBoxGainEnd = QtGui.QSpinBox(self.frame)
        self.spinBoxGainEnd.setEnabled(False)
        self.spinBoxGainEnd.setMaximum(255)
        self.spinBoxGainEnd.setProperty("value", 255)
        self.spinBoxGainEnd.setObjectName(_fromUtf8("spinBoxGainEnd"))
        self.horizontalLayout.addWidget(self.spinBoxGainEnd)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtGui.QFrame(self.frameControl)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setMinimumSize(QtCore.QSize(64, 0))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.spinBoxLineTime = QtGui.QSpinBox(self.frame_3)
        self.spinBoxLineTime.setObjectName(_fromUtf8("spinBoxLineTime"))
        self.horizontalLayout_3.addWidget(self.spinBoxLineTime)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtGui.QFrame(self.frameControl)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_8 = QtGui.QLabel(self.frame_4)
        self.label_8.setMinimumSize(QtCore.QSize(63, 0))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.spinBoxIntegrationTime = QtGui.QSpinBox(self.frame_4)
        self.spinBoxIntegrationTime.setObjectName(_fromUtf8("spinBoxIntegrationTime"))
        self.horizontalLayout_4.addWidget(self.spinBoxIntegrationTime)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtGui.QFrame(self.frameControl)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.checkBoxDarkPixelAveragin = QtGui.QCheckBox(self.frame_5)
        self.checkBoxDarkPixelAveragin.setObjectName(_fromUtf8("checkBoxDarkPixelAveragin"))
        self.horizontalLayout_5.addWidget(self.checkBoxDarkPixelAveragin)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.label_9 = QtGui.QLabel(self.frameControl)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self.treeView = QtGui.QTreeView(self.frameControl)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.verticalLayout_2.addWidget(self.treeView)
        self.horizontalLayout_7.addWidget(self.frameControl)
        self.frameImage = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameImage.sizePolicy().hasHeightForWidth())
        self.frameImage.setSizePolicy(sizePolicy)
        self.frameImage.setMinimumSize(QtCore.QSize(0, 0))
        self.frameImage.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameImage.setFrameShape(QtGui.QFrame.Panel)
        self.frameImage.setFrameShadow(QtGui.QFrame.Raised)
        self.frameImage.setObjectName(_fromUtf8("frameImage"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frameImage)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.labelImagePlaceholder = QtGui.QLabel(self.frameImage)
        self.labelImagePlaceholder.setText(_fromUtf8(""))
        self.labelImagePlaceholder.setPixmap(QtGui.QPixmap(_fromUtf8(":/imagery/example_heatmap.jpg")))
        self.labelImagePlaceholder.setScaledContents(True)
        self.labelImagePlaceholder.setObjectName(_fromUtf8("labelImagePlaceholder"))
        self.verticalLayout.addWidget(self.labelImagePlaceholder)
        self.horizontalLayout_7.addWidget(self.frameImage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Gain/Offset Configuration", None))
        self.labelMainTitle.setText(_translate("MainWindow", "Gain/Offset Configuration", None))
        self.toolButtonStart.setText(_translate("MainWindow", "Start", None))
        self.toolButtonStop.setText(_translate("MainWindow", "Stop", None))
        self.labelProcessing.setText(_translate("MainWindow", "Currently processing 1 out of 65536 combinations.", None))
        self.label_5.setText(_translate("MainWindow", "Offset:", None))
        self.label_6.setText(_translate("MainWindow", "to:", None))
        self.label_3.setText(_translate("MainWindow", "Gain:", None))
        self.label_4.setText(_translate("MainWindow", "to:", None))
        self.label_7.setText(_translate("MainWindow", "Line time:", None))
        self.label_8.setText(_translate("MainWindow", "Int. time:", None))
        self.checkBoxDarkPixelAveragin.setText(_translate("MainWindow", "Dark Pixel Averaging", None))
        self.label_9.setText(_translate("MainWindow", "Processing results:", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionOpen.setText(_translate("MainWindow", "Load", None))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))

import bbq_resources_rc
